var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_CURRENCY = "$";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_PAUSE = "PAUSE";
var TEXT_GAMEOVER = "YOU RUN OUT OF MONEY, WANT TO RECHARGE?";
var TEXT_BALLS_TO_PLAY = "YOU STILL HAVE SOME BALLS TO PLAY";

var TEXT_HELP1     = "LAUNCH A BALL IN ONE OF THE LUCKY HOLES TO GET THE CHANCE TO ENTER THE BONUS GAME";
var TEXT_HELP2     = "IN THE BONUS GAME, MATCH 3 IDENTICAL SYMBOLS TO GET A PRIZE";
var TEXT_PAYTABLE = "PAYTABLE";

var TEXT_DEVELOPED = "DEVELOPED BY";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";