(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("levelsettings",
{ "height":1,
 "infinite":false,
 "layers":[
        {
         "data":[0],
         "height":1,
         "name":"Livello tile 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":1,
         "x":0,
         "y":0
        }, 
        {
         "image":"..\/sprites\/bg_cat.png",
         "name":"layout",
         "opacity":0.55,
         "type":"imagelayer",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "image":"..\/sprites\/holes_mask.png",
         "name":"bottom",
         "offsetx":0,
         "offsety":880,
         "opacity":1,
         "type":"imagelayer",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"bonus_frame",
         "objects":[
                {
                 "height":0,
                 "id":78,
                 "name":"",
                 "polyline":[
                        {
                         "x":163,
                         "y":119.5
                        }, 
                        {
                         "x":93,
                         "y":95
                        }, 
                        {
                         "x":54.5,
                         "y":66.5
                        }, 
                        {
                         "x":27.5,
                         "y":36
                        }, 
                        {
                         "x":19,
                         "y":1.5
                        }, 
                        {
                         "x":18,
                         "y":-22
                        }, 
                        {
                         "x":25.5,
                         "y":-48
                        }, 
                        {
                         "x":37.5,
                         "y":-66.5
                        }, 
                        {
                         "x":90,
                         "y":-49
                        }, 
                        {
                         "x":105.5,
                         "y":-69.5
                        }, 
                        {
                         "x":55,
                         "y":-86.5
                        }, 
                        {
                         "x":82.3333,
                         "y":-106.167
                        }, 
                        {
                         "x":107.833,
                         "y":-119.667
                        }, 
                        {
                         "x":141.333,
                         "y":-133.667
                        }, 
                        {
                         "x":179.333,
                         "y":-144.167
                        }, 
                        {
                         "x":225,
                         "y":-150.5
                        }, 
                        {
                         "x":226,
                         "y":-104.5
                        }, 
                        {
                         "x":253.492,
                         "y":-105.026
                        }, 
                        {
                         "x":252.5,
                         "y":-150
                        }, 
                        {
                         "x":284.969,
                         "y":-145.778
                        }, 
                        {
                         "x":321.433,
                         "y":-136.215
                        }, 
                        {
                         "x":352,
                         "y":-125
                        }, 
                        {
                         "x":384,
                         "y":-110
                        }, 
                        {
                         "x":418.5,
                         "y":-86
                        }, 
                        {
                         "x":371,
                         "y":-67
                        }, 
                        {
                         "x":391,
                         "y":-47
                        }, 
                        {
                         "x":440.5,
                         "y":-66
                        }, 
                        {
                         "x":453.5,
                         "y":-40.5
                        }, 
                        {
                         "x":460.5,
                         "y":-15
                        }, 
                        {
                         "x":456,
                         "y":18.5
                        }, 
                        {
                         "x":439.5,
                         "y":50
                        }, 
                        {
                         "x":417,
                         "y":74
                        }, 
                        {
                         "x":373,
                         "y":99
                        }, 
                        {
                         "x":318.5,
                         "y":119
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":145,
                 "y":744
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"sensor_bonus",
         "objects":[
                {
                 "height":0,
                 "id":155,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":232,
                 "y":683
                }, 
                {
                 "height":0,
                 "id":156,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":384,
                 "y":628
                }, 
                {
                 "height":0,
                 "id":157,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":537,
                 "y":684.5
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"recover_basket",
         "objects":[
                {
                 "height":0,
                 "id":79,
                 "name":"",
                 "polyline":[
                        {
                         "x":0,
                         "y":0
                        }, 
                        {
                         "x":17.5,
                         "y":61
                        }, 
                        {
                         "x":42,
                         "y":61
                        }, 
                        {
                         "x":61,
                         "y":-0.5
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":628,
                 "y":463.5
                }, 
                {
                 "height":0,
                 "id":149,
                 "name":"",
                 "polyline":[
                        {
                         "x":-2.66667,
                         "y":-3.33333
                        }, 
                        {
                         "x":-5.16667,
                         "y":10.5
                        }, 
                        {
                         "x":7.16667,
                         "y":51.3333
                        }, 
                        {
                         "x":27.333,
                         "y":70.67
                        }, 
                        {
                         "x":47.333,
                         "y":76.0033
                        }, 
                        {
                         "x":58.6663,
                         "y":71.3367
                        }, 
                        {
                         "x":67.333,
                         "y":54.67
                        }, 
                        {
                         "x":63.9997,
                         "y":24.67
                        }, 
                        {
                         "x":46.6663,
                         "y":-7.99667
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":142.667,
                 "y":1093.33
                }, 
                {
                 "height":0,
                 "id":160,
                 "name":"",
                 "polyline":[
                        {
                         "x":-2.66667,
                         "y":-3.33333
                        }, 
                        {
                         "x":-5.16667,
                         "y":11.1667
                        }, 
                        {
                         "x":8.5,
                         "y":51.3333
                        }, 
                        {
                         "x":27.333,
                         "y":70.67
                        }, 
                        {
                         "x":52.6663,
                         "y":80.0033
                        }, 
                        {
                         "x":65.9996,
                         "y":71.3367
                        }, 
                        {
                         "x":72.6663,
                         "y":43.3367
                        }, 
                        {
                         "x":53.9997,
                         "y":-1.99667
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":273.333,
                 "y":1118
                }, 
                {
                 "height":0,
                 "id":161,
                 "name":"",
                 "polyline":[
                        {
                         "x":-5.33334,
                         "y":-2.66666
                        }, 
                        {
                         "x":-0.500003,
                         "y":29.8333
                        }, 
                        {
                         "x":13.8333,
                         "y":58
                        }, 
                        {
                         "x":38.6663,
                         "y":60.0033
                        }, 
                        {
                         "x":57.9997,
                         "y":44.67
                        }, 
                        {
                         "x":59.9996,
                         "y":6.00337
                        }, 
                        {
                         "x":51.333,
                         "y":-13.33
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":459.333,
                 "y":1122
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"sensor_basket",
         "objects":[
                {
                 "height":0,
                 "id":150,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":655.667,
                 "y":519
                }, 
                {
                 "height":0,
                 "id":152,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":492.666,
                 "y":1172.34
                }, 
                {
                 "height":0,
                 "id":153,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":324.999,
                 "y":1186.33
                }, 
                {
                 "height":0,
                 "id":154,
                 "name":"",
                 "point":true,
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":189.667,
                 "y":1159.67
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"pin",
         "objects":[
                {
                 "ellipse":true,
                 "height":34,
                 "id":9,
                 "name":"",
                 "rotation":0,
                 "type":"nose",
                 "visible":true,
                 "width":34,
                 "x":306,
                 "y":421
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":17,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":151.5,
                 "y":413
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":18,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":172,
                 "y":384.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":207,
                 "y":374.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":20,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":239.5,
                 "y":384
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":21,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":259,
                 "y":403.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":33,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":375.25,
                 "y":388.75
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":34,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":394.25,
                 "y":361.25
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":35,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":427.25,
                 "y":347.75
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":36,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":460.75,
                 "y":351.25
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":37,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":484.25,
                 "y":374.75
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":39,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":102.5,
                 "y":471.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":40,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":134.5,
                 "y":474
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":42,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":102.5,
                 "y":506
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":43,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":132,
                 "y":506
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":45,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":117,
                 "y":539
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":46,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":148,
                 "y":532
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":47,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":507.5,
                 "y":430
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":48,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":535,
                 "y":425
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":49,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":562,
                 "y":413.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":50,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":512,
                 "y":464
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":51,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":541.5,
                 "y":462
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":52,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":570.5,
                 "y":454.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":54,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":518.5,
                 "y":498.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":55,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":549,
                 "y":497
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":56,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":436.5,
                 "y":267.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":57,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":435.5,
                 "y":298.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":58,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":467,
                 "y":302
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":59,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":480.5,
                 "y":275
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":61,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":178.5,
                 "y":329.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":62,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":144.5,
                 "y":344
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":64,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":616.5,
                 "y":383.167
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":65,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":616,
                 "y":416.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":66,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":649.333,
                 "y":380.167
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":67,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":649.5,
                 "y":413.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":68,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":681,
                 "y":384
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":69,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":682,
                 "y":415
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":70,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":325,
                 "y":472
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":71,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":364.5,
                 "y":471
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":72,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":282,
                 "y":481
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":97,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":153.25,
                 "y":1021
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":98,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":99.25,
                 "y":817.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":99,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":87.25,
                 "y":745
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":100,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":91.75,
                 "y":857.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":101,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":78.75,
                 "y":914
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":102,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":114.75,
                 "y":905.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":104,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":281.25,
                 "y":1014
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":105,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":50.25,
                 "y":893.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":107,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":138.25,
                 "y":813
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":108,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":188.75,
                 "y":945.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":109,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":220.75,
                 "y":929.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":110,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":158.25,
                 "y":845
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":111,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":235.25,
                 "y":1020
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":112,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":125.75,
                 "y":865.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":113,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":251.75,
                 "y":968
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":114,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":160.25,
                 "y":908.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":115,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":98.75,
                 "y":993
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":116,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":115.25,
                 "y":1033
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":117,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":189.25,
                 "y":887.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":118,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":214.25,
                 "y":980.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":119,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":120.25,
                 "y":944
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":120,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":84.75,
                 "y":958
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":121,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":131.25,
                 "y":981
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":128,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":617.25,
                 "y":810.75
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":129,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":630.5,
                 "y":862.75
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":130,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":582,
                 "y":854.25
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":131,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":581.5,
                 "y":927.75
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":132,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":603.5,
                 "y":898.25
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":133,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":548,
                 "y":894
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":134,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":561.5,
                 "y":963.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":135,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":541,
                 "y":1000
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":136,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":524,
                 "y":1034
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":138,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":522,
                 "y":937
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":139,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":496.5,
                 "y":971
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":140,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":480,
                 "y":1010
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":143,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":481.5,
                 "y":897.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":144,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":455.5,
                 "y":940
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":145,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":434.5,
                 "y":974
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":146,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":415.5,
                 "y":1015.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":158,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":603,
                 "y":475
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":159,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":599,
                 "y":508
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"edge_frame",
         "objects":[
                {
                 "height":0,
                 "id":6,
                 "name":"",
                 "polyline":[
                        {
                         "x":-330.667,
                         "y":-199
                        }, 
                        {
                         "x":-282.667,
                         "y":-414.667
                        }, 
                        {
                         "x":-282.667,
                         "y":-461.333
                        }, 
                        {
                         "x":-275.333,
                         "y":-531.333
                        }, 
                        {
                         "x":-291.667,
                         "y":-561
                        }, 
                        {
                         "x":-305.417,
                         "y":-596.25
                        }, 
                        {
                         "x":-314.667,
                         "y":-657.5
                        }, 
                        {
                         "x":-309.667,
                         "y":-723.667
                        }, 
                        {
                         "x":-298.667,
                         "y":-758.666
                        }, 
                        {
                         "x":-302.666,
                         "y":-873.333
                        }, 
                        {
                         "x":-272,
                         "y":-906.667
                        }, 
                        {
                         "x":-170.667,
                         "y":-880
                        }, 
                        {
                         "x":-70.6667,
                         "y":-904
                        }, 
                        {
                         "x":13.3333,
                         "y":-902.667
                        }, 
                        {
                         "x":81.3333,
                         "y":-958.667
                        }, 
                        {
                         "x":116,
                         "y":-964
                        }, 
                        {
                         "x":145.333,
                         "y":-942.667
                        }, 
                        {
                         "x":169.333,
                         "y":-888
                        }, 
                        {
                         "x":204,
                         "y":-766.667
                        }, 
                        {
                         "x":246.667,
                         "y":-774.667
                        }, 
                        {
                         "x":292,
                         "y":-768
                        }, 
                        {
                         "x":329.333,
                         "y":-733.333
                        }, 
                        {
                         "x":340,
                         "y":-706.667
                        }, 
                        {
                         "x":329.333,
                         "y":-592
                        }, 
                        {
                         "x":328,
                         "y":-462.667
                        }, 
                        {
                         "x":270.667,
                         "y":-348
                        }, 
                        {
                         "x":302.667,
                         "y":-194.666
                        }],
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":380,
                 "y":1100
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "name":"temp_todelete",
         "objects":[
                {
                 "ellipse":true,
                 "height":8,
                 "id":122,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":180.5,
                 "y":1064
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":123,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":138,
                 "y":1070.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":124,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":303.5,
                 "y":1058.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":125,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":257.5,
                 "y":1064.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":137,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":504.5,
                 "y":1069.5
                }, 
                {
                 "ellipse":true,
                 "height":8,
                 "id":141,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":8,
                 "x":451.5,
                 "y":1054
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "x":0,
         "y":0
        }],
 "nextobjectid":162,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"2018.03.21",
 "tileheight":1280,
 "tilesets":[],
 "tilewidth":768,
 "type":"map",
 "version":1.2,
 "width":1
});