var CANVAS_WIDTH = 768;
var CANVAS_HEIGHT = 1280;

var CANVAS_WIDTH_HALF = CANVAS_WIDTH/2;
var CANVAS_HEIGHT_HALF = CANVAS_HEIGHT/2;

var EDGEBOARD_X = 100;
var EDGEBOARD_Y = 140;

var GAME_NAME = "pinball";

var PRIMARY_FONT = "walibi0615bold";

var PRIMARY_FONT_COLOUR = "#fff600";

var SOUNDTRACK_VOLUME_IN_GAME = 0.1; 

var FPS           = 60;
var FPS_TIME      = 1000/FPS;
var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_EXIT_HELP   = 6;

var WHEEL_STATE_IDLE = 0;
var WHEEL_STATE_SPINNING = 1;
var WHEEL_STATE_SHOW_WIN = 2;

var REEL_STATE_START   = 0;
var REEL_STATE_MOVING = 1;
var REEL_STATE_STOP    = 2;

var ON_REEL_ARRIVED = 0;
var ON_REEL_STOP = 1;


var ON_WHEEL_READY_TO_SPIN = 0;
var ON_WHEEL_STOP = 1;
var ON_WHEEL_CLOSED = 2;
var ON_WHEEL_WIN = 3;

var ON_SENSOR_BASKET = 0;
var ON_SENSOR_BONUS = 1;

var ON_CONTROLLER = 0;

var CONTACT_BEGIN = 0;
var CONTACT_END = 1;
var CONTACT_PRESOLVE = 2;
var CONTACT_POSTSOLVE = 3;

var SETTINGS_HEIGHT = 240;

var TODEGREE_PROPORTION = 180/Math.PI;
var ZOOM_TABLE_SIZE = {w:1, h:1};
var BALL_OUT_SAFE_LIMIT = 40;

////////BOX 2D SETTINGS
var DEBUG_BOX2D = false;
var DEBUG_BOX2D_ALPHA = 0.8;
var WORLD_SCALE = 100;
var GRAVITY = 13.6;
var GENERAL_RESTITUTION = 0.3;
var GENERAL_FRICTION = 0.7;
var ZOOM = 1;
var ZOOM_PER_WORLDSCALE = ZOOM*WORLD_SCALE;

////////BALL SETTINGS
var BALL_STARTPOS_GAME = {x: 115-CANVAS_WIDTH/2, y: 308-CANVAS_HEIGHT/2};
var BALL_STARTPOS_WORLD = {x: BALL_STARTPOS_GAME.x/WORLD_SCALE, y: BALL_STARTPOS_GAME.y/WORLD_SCALE};
var BALL_RADIUS = 10;

////////CAMERA SETTINGS
var LERP_SLOW = {x: 0.01, y:0.01};
var LERP_FOLLOW_BALL = {x: 0.05, y:0.15};

////////GAME SETTINGS
var ALLOW_BET_WHILEPLAYING = true;
var BALL_SPAWN_TIMER = 400;
var BALL_POOL_DIM = 20;
var START_CREDITS;
var BALLS_PER_BET;
var BET;
var WIN_PERCENTAGE;
var PAYTABLE;
var BANK;

////////BONUS SETTINGS
var SYMBOL_WIDTH = 78; 
var SYMBOL_HEIGHT =  97;
var NUM_SYMBOLS = 3;
var SPACE_BETWEEN_SYMBOLS = 26;
var SPACE_HEIGHT_BETWEEN_SYMBOLS = 0;
var SCALE_SYMBOL = 1;
var NUM_ROWS = 1;
var NUM_REELS = 3;
var REEL_OFFSET_X = -144;
var REEL_OFFSET_Y = -12;
var REEL_DELAY = 20;
var MAX_FRAMES_REEL_EASE = 7;
var OFFSET_LIMIT_Y = 0;
var REEL_START_Y = REEL_OFFSET_Y - ((SYMBOL_HEIGHT +SPACE_HEIGHT_BETWEEN_SYMBOLS )* NUM_ROWS);
var REEL_ARRIVAL_Y = REEL_OFFSET_Y + ((SYMBOL_HEIGHT+SPACE_HEIGHT_BETWEEN_SYMBOLS) * NUM_ROWS) -OFFSET_LIMIT_Y;
var MIN_REEL_LOOPS = 4;
var ANIM_WIN_LOOPS = 4;
var WHEEL_WINNING_COMBO = [ 
    ////THE NUMBER IS THE INDEX OF THE SYMBOL
    [0,0,0],
    [1,1,1],
    [2,2,2]
];



var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;





 
